// Auto-generated by scripts/fetch-data.ts — do not edit
import type { Experiment } from "./types";
export const experiments: Experiment[] = [] as Experiment[];
export const tags: { tag: string; count: number }[] = [];
