name = "terminus-ink"
compatibility_date = "2026-04-07"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".worker/static"

[vars]
NEXT_PUBLIC_API_URL = "https://api.terminus.ink"
NEXT_PUBLIC_SUPABASE_URL = "https://fxlpelewdkugkthcvazi.supabase.co"
NEXT_PUBLIC_SUPABASE_ANON_KEY = "sb_publishable_zve6Ro59kiEyS0oWK7TmdQ_qoATOaXm"
