import { mkdirSync, writeFileSync } from "fs";

const API_URL = process.env.NEXT_PUBLIC_API_URL || "https://api.terminus.ink";

async function fetchData() {
  console.log(`Fetching data from ${API_URL}...`);

  const [experiments, tags] = await Promise.all([
    fetch(`${API_URL}/api/experiments?limit=100`)
      .then((r) => r.json())
      .catch(() => []),
    fetch(`${API_URL}/api/tags`)
      .then((r) => r.json())
      .catch(() => []),
  ]);

  writeDataModule(experiments, tags);

  // Also write JSON for feed generator
  mkdirSync(".generated", { recursive: true });
  writeFileSync(".generated/experiments.json", JSON.stringify(experiments, null, 2));

  console.log(
    `Fetched ${experiments.length} experiments, ${tags.length} tags`
  );
}

function writeDataModule(experiments: unknown[], tags: unknown[]) {
  const content = `// Auto-generated by scripts/fetch-data.ts — do not edit
import type { Experiment } from "./types";
export const experiments: Experiment[] = ${JSON.stringify(experiments, null, 2)} as Experiment[];
export const tags: { tag: string; count: number }[] = ${JSON.stringify(tags, null, 2)};
`;
  writeFileSync("src/lib/data.gen.ts", content);
}

fetchData().catch((err) => {
  console.error("Failed to fetch data:", err.message);
  // Don't fail the build — write empty module
  writeDataModule([], []);
  mkdirSync(".generated", { recursive: true });
  writeFileSync(".generated/experiments.json", "[]");
  console.log("Using empty data fallback.");
});
